"""Assemble the full Markdown report and a short chat summary from all pipeline outputs.

从全部流程产物汇编完整 Markdown 报告与一段简短对话总结。

Sections: annotation results (totals, pos/neg split, confidence grading, score distributions),
quality control, all differential analyses (with embedded figures), and the biological conclusions
with their multi-agent verification. Text follows the chosen language.

章节：注释结果（总量、正负离子分别情况、置信度分级、打分分布）、质量控制、全部差异分析（含内嵌
图）、生物学结论及其多智能体验证。文字使用所选语言。
"""

import os


def _h(language, en, zh):
    return zh if language == "zh" else en


def _img(md_dir, path, caption):
    if not path or not os.path.exists(path):
        return ""
    rel = os.path.relpath(path, md_dir).replace("\\", "/")
    return f"![{caption}]({rel})\n\n"


def _fmt_dict(d):
    return ", ".join(f"{k}={v}" for k, v in d.items())


def build_report(md_path, language, params, annotation_overview, qc_results,
                 analyses, conclusions, verifications, extra_paths=None, sample_context=None):
    md_dir = os.path.dirname(os.path.abspath(md_path))
    L = language
    lines = []

    lines.append("# " + _h(L, "LipidIN Lipidomics Analysis Report",
                            "LipidIN 脂质组学分析报告"))
    lines.append("")
    lines.append(_h(L, "This report is auto-generated by the LipidIN agent, covering annotation, "
                      "quality control, differential analysis and biologically-verified conclusions.",
                    "本报告由 LipidIN 智能体自动生成，涵盖注释、质量控制、差异分析以及经验证的生物学结论。"))
    lines.append("")

    # ---------------- 1. Annotation ---------------- #
    lines.append("## 1. " + _h(L, "Annotation results", "注释结果"))
    if annotation_overview:
        lines.append(_h(L, f"**Total annotations:** {annotation_overview['total_annotations']}",
                        f"**总注释量：** {annotation_overview['total_annotations']}"))
        lines.append("")
        lines.append(_h(L, "**Per-polarity counts:** ", "**正负离子分别情况：** ")
                     + _fmt_dict(annotation_overview.get("per_polarity", {})))
        lines.append("")
        lines.append(_h(L, "**Evidence types:** ", "**证据类型：** ")
                     + _fmt_dict(annotation_overview.get("evidence_counts", {})))
        lines.append("")
        lines.append(_h(L, "**Confidence grades:** ", "**置信度分级：** ")
                     + _fmt_dict(annotation_overview.get("grade_counts", {})))
        lines.append("")
        for detail in annotation_overview.get("polarity_details", []):
            lines.append(f"### 1.{detail['polarity']} " + _h(L, f"Polarity {detail['polarity']}",
                                                             f"极性 {detail['polarity']}"))
            lines.append(_h(L, f"- Annotations: {detail['total_annotations']}, "
                              f"subclasses: {detail['n_subclasses']}",
                            f"- 注释数：{detail['total_annotations']}，脂质类别数：{detail['n_subclasses']}"))
            lines.append(_h(L, f"- Cosine similarity (median/mean): "
                              f"{detail['cosine_similarity']['median']}/{detail['cosine_similarity']['mean']}",
                            f"- 余弦相似度（中位/均值）："
                            f"{detail['cosine_similarity']['median']}/{detail['cosine_similarity']['mean']}"))
            lines.append(_h(L, f"- IoU (median/mean): "
                              f"{detail['intersection_over_union']['median']}/{detail['intersection_over_union']['mean']}",
                            f"- IoU（中位/均值）："
                            f"{detail['intersection_over_union']['median']}/{detail['intersection_over_union']['mean']}"))
            lines.append(_h(L, f"- RT-fit score (median/mean): "
                              f"{detail['rt_fit_score']['median']}/{detail['rt_fit_score']['mean']}",
                            f"- RT 拟合分（中位/均值）："
                            f"{detail['rt_fit_score']['median']}/{detail['rt_fit_score']['mean']}"))
            lines.append(_h(L, "- Grades: ", "- 分级：") + _fmt_dict(detail["grade_counts"]))
            lines.append("")

    # ---------------- 2. QC ---------------- #
    lines.append("## 2. " + _h(L, "Quality control", "质量控制"))
    for polarity, qc in (qc_results or {}).items():
        lines.append(f"### 2.{polarity} " + _h(L, f"QC ({polarity})", f"质控（{polarity}）"))
        cv = qc.get("cv", {})
        if cv.get("n_features_evaluated"):
            lines.append(_h(L, f"- CV on {len(cv['qc_samples'])} QC samples, "
                              f"{cv['n_features_evaluated']} features, median CV {cv['median_cv_percent']:.1f}%, "
                              f"CV<30% {cv['fraction_cv_below_30']:.1f}%, CV<20% {cv['fraction_cv_below_20']:.1f}%",
                            f"- 基于 {len(cv['qc_samples'])} 个 QC 样本，{cv['n_features_evaluated']} 个特征，"
                            f"CV 中位 {cv['median_cv_percent']:.1f}%，CV<30% 占 {cv['fraction_cv_below_30']:.1f}%，"
                            f"CV<20% 占 {cv['fraction_cv_below_20']:.1f}%"))
        pca = qc.get("pca", {})
        if pca.get("explained_variance_percent"):
            var = pca["explained_variance_percent"]
            lines.append(_h(L, f"- PCA explained variance: "
                              + ", ".join(f"PC{i+1}={v:.1f}%" for i, v in enumerate(var)),
                            f"- PCA 解释方差："
                            + "，".join(f"PC{i+1}={v:.1f}%" for i, v in enumerate(var))))
        plsda = qc.get("plsda", {})
        if plsda:
            lines.append(_h(L, f"- PLS-DA: R2Y={plsda['r2y']:.3f}, Q2={plsda['q2']:.3f}, "
                              f"accuracy={plsda['accuracy_percent']:.1f}%",
                            f"- PLS-DA：R2Y={plsda['r2y']:.3f}，Q2={plsda['q2']:.3f}，"
                            f"准确率={plsda['accuracy_percent']:.1f}%"))
        lines.append("")
        lines.append(_img(md_dir, cv.get("cv_png"), f"QC CV {polarity}"))
        lines.append(_img(md_dir, pca.get("pca_png"), f"PCA {polarity}"))
        lines.append(_img(md_dir, plsda.get("plsda_png"), f"PLS-DA {polarity}"))

    # ---------------- 3. Differential ---------------- #
    lines.append("## 3. " + _h(L, "Differential analysis", "差异分析"))
    for analysis in (analyses or []):
        tag = analysis["tag"]
        lines.append(f"### 3.{tag} " + _h(L, f"{analysis['case']} vs {analysis['control']} ({tag})",
                                          f"{analysis['case']} vs {analysis['control']}（{tag}）"))
        lines.append(_h(L, f"- Features tested: {analysis['n_features']}, significant: "
                          f"{analysis['n_significant']} (up {analysis['n_up']}, down {analysis['n_down']})",
                        f"- 检验特征：{analysis['n_features']}，显著：{analysis['n_significant']}"
                        f"（上调 {analysis['n_up']}，下调 {analysis['n_down']}）"))
        rf = analysis.get("random_forest") or {}
        if rf:
            lines.append(_h(L, f"- Random forest: CV accuracy {rf.get('cv_accuracy')}, AUC {rf.get('cv_auc')}",
                            f"- 随机森林：交叉验证准确率 {rf.get('cv_accuracy')}，AUC {rf.get('cv_auc')}"))
        lines.append("")
        plots = analysis.get("plots", {})
        lines.append(_img(md_dir, plots.get("volcano"), f"Volcano {tag}"))
        lines.append(_img(md_dir, plots.get("heatmap"), f"Heatmap {tag}"))
        lines.append(_img(md_dir, plots.get("fatty_acid_change"), f"FA change {tag}"))
        lines.append(_img(md_dir, plots.get("class_bubble"), f"Class bubble {tag}"))
        lines.append(_img(md_dir, plots.get("random_forest"), f"Random forest {tag}"))

        # LIPID MAPS pathway enrichment / LIPID MAPS 代谢通路富集
        pathways = analysis.get("pathways") or {}
        enrich = pathways.get("enrichment") or []
        if enrich:
            lines.append("**" + _h(L, "LIPID MAPS pathway enrichment", "LIPID MAPS 代谢通路富集") + "**")
            lines.append("")
            lines.append(_img(md_dir, plots.get("pathway_enrichment"), f"Pathway enrichment {tag}"))
            lines.append("| " + _h(L, "Pathway", "通路") + " | " + _h(L, "sig/total", "显著/总")
                         + " | " + _h(L, "mean log2FC", "平均log2FC") + " | " + _h(L, "enrich p", "富集p")
                         + " | " + _h(L, "subclasses", "亚类") + " |")
            lines.append("|---|---|---|---|---|")
            for e in enrich[:10]:
                name = e["name_zh"] if L == "zh" else e["name_en"]
                p_txt = ("%.1e" % e["enrich_p"]) if e.get("enrich_p") == e.get("enrich_p") else "NA"
                lines.append(f"| {name} | {int(e['n_sig'])}/{int(e['n_features'])} | {e['mean_log2fc']} "
                             f"| {p_txt} | {e['subclasses']} |")
            lines.append("")

        if analysis["top_up"]:
            lines.append("**" + _h(L, "Top up-regulated", "上调 Top") + "**")
            lines.append("")
            lines.append("| " + _h(L, "Lipid", "脂质") + " | subclass | log2FC | FDR | evidence |")
            lines.append("|---|---|---|---|---|")
            for c in analysis["top_up"][:10]:
                lines.append(f"| {c['name']} | {c['subclass']} | {c['log2fc']} | "
                             f"{c['fdr']:.2e} | {c['evidence_type']} |")
            lines.append("")
        if analysis["top_down"]:
            lines.append("**" + _h(L, "Top down-regulated", "下调 Top") + "**")
            lines.append("")
            lines.append("| " + _h(L, "Lipid", "脂质") + " | subclass | log2FC | FDR | evidence |")
            lines.append("|---|---|---|---|---|")
            for c in analysis["top_down"][:10]:
                lines.append(f"| {c['name']} | {c['subclass']} | {c['log2fc']} | "
                             f"{c['fdr']:.2e} | {c['evidence_type']} |")
            lines.append("")

    # ---------------- 4. Conclusions + verification ---------------- #
    lines.append("## 4. " + _h(L, "Biological conclusions and verification",
                               "生物学结论与验证"))
    if sample_context:
        lines.append(_h(L, f"**Study context:** {sample_context}",
                        f"**研究背景：** {sample_context}"))
        lines.append("")
    verifications = verifications or []
    for i, verification in enumerate(verifications):
        conclusion = verification["conclusion"]
        lines.append(f"### 4.{i+1} " + _h(L, f"Conclusion {conclusion['id']}",
                                          f"结论 {conclusion['id']}"))
        lines.append("> " + conclusion["statement"])
        lines.append("")
        if conclusion.get("rationale"):
            lines.append(_h(L, "**Rationale:** ", "**依据：** ") + conclusion["rationale"])
            lines.append("")
        if conclusion.get("involved_pathways"):
            lines.append(_h(L, "**LIPID MAPS pathways:** ", "**LIPID MAPS 通路：** ")
                         + ", ".join(str(p) for p in conclusion["involved_pathways"]))
            lines.append("")
        if "error" in verification:
            lines.append(_h(L, f"Verification error: {verification['error']}",
                            f"验证出错：{verification['error']}"))
            lines.append("")
            continue
        lines.append(_h(L, f"**Overall verdict:** {verification['verdict']} "
                          f"(score {verification['overall_score']})",
                        f"**总体判定：** {verification['verdict']}（评分 {verification['overall_score']}）"))
        lines.append("")
        ann = verification["annotation_confidence"]
        rt = verification["rt_confidence"]
        bio = verification["biological_support"]
        lit = verification["similar_reports"]
        lines.append("| " + _h(L, "Dimension", "维度") + " | " + _h(L, "Score", "评分")
                     + " | " + _h(L, "Detail", "说明") + " |")
        lines.append("|---|---|---|")
        lines.append(f"| " + _h(L, "Annotation confidence", "注释可信度") + f" | {ann['score']} ({ann['level']}) | {ann['detail']} |")
        lines.append(f"| " + _h(L, "RT confidence", "RT 可信度") + f" | {rt['score']} ({rt['level']}) | {rt['detail']} |")
        lines.append(f"| " + _h(L, "Biological support", "生物结论支撑度") + f" | {bio['score']} | {bio['comment']} |")
        lines.append(f"| " + _h(L, "Similar reports", "相似报道") + f" | {lit['score']} | "
                     + _h(L, f"{lit['n_references']} refs found; {lit['comment']}",
                          f"检索到 {lit['n_references']} 篇；{lit['comment']}") + " |")
        lines.append("")
        if lit.get("references"):
            lines.append(_h(L, "**Related references:**", "**相关文献：**"))
            for ref in lit["references"][:5]:
                lines.append(f"- {ref.get('title','')} ({ref.get('year','')}, {ref.get('journal','')}; "
                             f"DOI {ref.get('doi','')})")
            lines.append("")

    # ---------------- 5. Appendix ---------------- #
    lines.append("## 5. " + _h(L, "Appendix: parameters", "附录：参数"))
    lines.append("```")
    for k, v in (params or {}).items():
        lines.append(f"{k} = {v}")
    for k, v in (extra_paths or {}).items():
        lines.append(f"{k} = {v}")
    lines.append("```")

    content = "\n".join(lines)
    with open(md_path, "w", encoding="utf-8") as f:
        f.write(content)
    return md_path


def build_short_summary(language, annotation_overview, qc_results, analyses, verifications):
    """Return a brief, detail-free summary string for the chat window.

    返回一段简短、不含细节的总结字符串，用于对话框。
    """
    L = language
    parts = []
    if annotation_overview:
        parts.append(_h(L, f"Annotations: {annotation_overview['total_annotations']} total "
                          f"({_fmt_dict(annotation_overview.get('per_polarity', {}))}).",
                        f"注释：共 {annotation_overview['total_annotations']} 条"
                        f"（{_fmt_dict(annotation_overview.get('per_polarity', {}))}）。"))
    qc_bits = []
    for polarity, qc in (qc_results or {}).items():
        cv = qc.get("cv", {})
        if cv.get("n_features_evaluated"):
            qc_bits.append(f"{polarity} CV<30% {cv['fraction_cv_below_30']:.0f}%")
    if qc_bits:
        parts.append(_h(L, "QC: " + ", ".join(qc_bits) + ".",
                        "质控：" + "，".join(qc_bits) + "。"))
    for analysis in (analyses or []):
        parts.append(_h(L, f"Differential ({analysis['case']} vs {analysis['control']}): "
                          f"{analysis['n_significant']} significant lipids "
                          f"(up {analysis['n_up']}, down {analysis['n_down']}).",
                        f"差异（{analysis['case']} vs {analysis['control']}）："
                        f"{analysis['n_significant']} 个显著脂质（上调 {analysis['n_up']}，下调 {analysis['n_down']}）。"))
    if verifications:
        supported = sum(1 for v in verifications if v.get("overall_score", 0) >= 0.45)
        parts.append(_h(L, f"Conclusions: {len(verifications)} proposed, {supported} at least moderately supported.",
                        f"结论：提出 {len(verifications)} 条，其中 {supported} 条至少中等支撑。"))
    return "\n".join(parts)
